FROM registry.fedoraproject.org/f35/s2i-core

# Variables de ambiente requeridas por el contenedor

RUN { yum -y module enable postgresql:16 || :; } && \
    # INSTALL_PKGS="rsync tar gettext bind-utils nss_wrapper-libs postgresql-server postgresql-contrib" && \
    INSTALL_PKGS="rsync tar gettext bind-utils postgresql-server postgresql-contrib" && \
    INSTALL_PKGS="$INSTALL_PKGS pgaudit" && \
    INSTALL_PKGS="$INSTALL_PKGS procps-ng util-linux postgresql-upgrade" && \
    yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    postgres -V | grep -qe "$POSTGRESQL_VERSION\." && echo "Found VERSION $POSTGRESQL_VERSION" && \
    (yum -y reinstall tzdata || yum -y update tzdata ) && \
    yum -y clean all --enablerepo='*'
#   yum -y clean all --enablerepo='*' &&
#    localedef -f UTF-8 -i en_US en_US.UTF-8 && \
#    test "$(id postgres)" = "uid=26(postgres) gid=26(postgres) groups=26(postgres)" && \
#    mkdir -p /var/lib/pgsql/data && \
#    mkdir -p /run/postgresql && \
#    /usr/libexec/fix-permissions /var/lib/pgsql /run/postgresql

# Get prefix path and path to scripts rather than hard-code them in scripts
ENV CONTAINER_SCRIPTS_PATH=/usr/share/container-scripts/postgresql \
    ENABLED_COLLECTIONS=

COPY root /
COPY ./s2i/bin/ $STI_SCRIPTS_PATH

RUN ln -s /usr/bin/run-postgresql $STI_SCRIPTS_PATH/run

RUN usermod -a -G root postgres && \
    /usr/libexec/fix-permissions --read-only "$APP_DATA"

EXPOSE 5432

USER 26

ENTRYPOINT ["container-entrypoint"]
CMD ["run-postgresql"]